# -*- coding: utf-8 -*-
"""11월 4주차.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IP5Ic35tyhkFt5TTDDOr8GUrB7twDtis
"""

# 백준 별찍기 8
num = int(input())
cnt = 1
for i in range(2*num-1):#9
  if i < num:#별 쫙 있는거 포함 상위
    print((cnt)*'*',end = '')
    for j in range(2*(num-cnt)):#num5기준 빈칸 8,6,4,2,0
      print(' ', end ='')
    print((cnt)*'*',end='')
    print()
    cnt += 1
    #넘 5, i =4 cnt 6

  else:    #별 쫙 있는거 기준 하위
    cnt -= 1
    print((cnt-1)*'*',end = '')
    for j in range(2*(num-cnt+1)):#num5기준 빈칸 2,4,6,8
      print(' ',end = '')
    print((cnt-1)*'*',end='')
    print()

a, b = map(int, input().split())  # 첫 번째 입력: 배열 크기
x = []

# 두 번째 입력: 여러 줄 배열 복붙
for _ in range(a):
    row = input().strip()  # 한 줄 입력받기
    x.append(list(row[:b]))  # 글자 단위로 나누어 리스트로 저장

print(x)

